tools:
  - class_name: verl.tools.search_tool.SearchTool
    config:
      retrieval_service_url: http://10.244.209.173:8000/retrieve
      num_workers: 1
      rate_limit: 2
      timeout: 60
      enable_global_rate_limit: true
      type: native
    tool_schema:
      type: function
      function:
        name: search
        description: Searches the web for relevant information based on the given query.
        parameters:
          type: object
          properties:
            query:
              type: string
              description: A fully-formed semantic query string. The tool will return search results for this query.
            topk:
              type: integer
              description: Number of top results to return. Default is 5.
              default: 5
          required:
            - query