# ALFWorld Base Configuration for VERL
# TextWorld environment configuration

env:
  type: 'AlfredTWEnv'
  task_types: [1, 2, 3, 4, 5, 6]
  domain_randomization: false
  max_nb_steps_per_episode: 50
  regen_game_files: false
  goal_desc_human_anns_prob: 0.0
  expert_type: 'handcoded'
  expert_timeout_steps: 150
  expert_timeout_penalty: 0.0
  step_limit: 50
  
dataset:
  data_path: '$ALFWORLD_DATA/json_2.1.1/train'
  eval_ood_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_unseen'
  eval_id_data_path: '$ALFWORLD_DATA/json_2.1.1/valid_seen'
  num_train_games: -1
  num_eval_games: -1

logic:
  domain: '$ALFWORLD_DATA/logic/alfred.pddl'
  grammar: '$ALFWORLD_DATA/logic/alfred.twl2'

general:
  random_seed: 42
  use_cuda: false
  training_method: 'dagger'
  use_pretrained: false
  load_pretrained: false
  save_path: '/tmp/alfworld'
  observation_type: 'text'
  visdom: false
  tensorboard: false

expert:
  expert_timeout_steps: 150
  expert_type: 'handcoded'

dagger:
  training:
    max_nb_steps_per_episode: 50
    learn_start_from_zero: false
    batch_size: 10

evaluate:
  eval_max_nb_steps_per_episode: 50
  envs:
    batch_size: 1
